default:
  logo: /assets/img/modules/mayi.png
  name: Final Framework
menus:
  - id: index
    name: README
    icon: dashboard
    link: /
  - id: data
    name: Data
    icon: table_chart
    menus:
      - id: enum
        link: /data/enum
        mini: EM
        name: Enum
      - id: repository
        mini: CURD
        name: Repository
        menus:
          - id: index
            name: README
            link: /data/repository/
            mini: RD
          - id: create
            name: Create
            link: /data/repository/create
            mini: C
          - id: retrieve
            name: Retrieve
            link: /data/repository/retrieve
            mini: R
          - id: update
            name: Update
            link: /data/repository/update
            mini: U
          - id: delete
            name: Delte
            link: /data/repository/delete
            mini: D
      - id: criterion
        link: /data/criterion
        mini: CTN
        name: Criterion
