build:
  environment:
    java: 'java-8-oracle'
  nodes:
    tests-with-coverage:
      resources:
        cpus: 4
      tests:
        override:
          - command: mvn clean package
            coverage:
              file: '/'
              format: 'jacoco'
checks:
  java: true