build:
  environment:
    java: 'java-8-oracle'
  nodes:
    coverage:
      tests:
        override:
          - command: mvn clean package
            coverage:
              file: '/'
              format: 'jacoco'
checks:
  java: true