build:
  environment:
    java: 'java-8-oracle'
  nodes:
    tests-with-coverage:
      tests:
        override:
          - command: mvn clean package
            coverage:
              file: '[path-to-coverage-reports]'
              format: 'jacoco'
checks:
  java: true