language: java

after_script:
  - git push --force "https://likly:9741788be93d1d75556f8a5b7544ca184bcc7e64@git.coding.net/likly/final-framework.git" master:master


branches:
  only:
    - master

env:
  global:
    coding_user: likly
    coding_repo: git.coding.net/likly/final-framework.git