spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&verifyServerCertificate=false&useSSL=false&requireSSL=false
    username: root
    password: Aa000000
    type: com.zaxxer.hikari.HikariDataSource
  redis:
    host: localhost
    port: 6379
    timeout: 20000
  mail:
    host: smtp.exmail.qq.com
    username: noreply@likly.com.cn
    password: Qq0000
  jackson:
    default-property-inclusion: non_null
  #    date-format: yyyy-MM-dd HH:mm:ss
  aop:
    proxy-target-class: true
  transaction:
    rollback-on-commit-failure: true
  application:
    name: final-test
pagehelper:
  auto-dialect: true
  close-conn: true
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: pageNum=page;size=size
logging:
  level:
    org.finalframework: info
    org.finalframework.test.dao: debug
    org.springframework: info
  file: classpath:logback-srping.xml
server:
  port: 8080
final:
  data:
    name-converter:
      column-converter: org.finalframework.data.mapping.converter.SimpleNameConverter
      table-converter: org.finalframework.data.mapping.converter.SimpleNameConverter
    column-generator:
      default-column-generator: org.finalframework.mybatis.generator.DefaultColumnGenerator
  json:
    json-service: org.finalframework.json.jackson.JacksonJsonService
  response:
    sync-status: true
    default-interceptor: org.finalframework.spring.web.reponse.ResultResponseBodyInterceptor
  monitor:
    action:
      logger: org.finalframework.test.monitor.action.handler
  exception:
    logger: org.finalframework.test.error
mybatis:
  mapper-locations: classpath:org/finalframework/test/dao/mapper/*Mapper.xml
