spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&verifyServerCertificate=false&useSSL=false&requireSSL=false
    username: root
    password: Aa000000
    type: com.zaxxer.hikari.HikariDataSource
  redis:
    host: localhost
    port: 6379
    timeout: 20000
  mail:
    host: smtp.exmail.qq.com
    username: noreply@likly.com.cn
    password: Qq0000
  jackson:
    default-property-inclusion: non_null
  #    date-format: yyyy-MM-dd HH:mm:ss
  aop:
    proxy-target-class: true
  transaction:
    rollback-on-commit-failure: true
  application:
    name: final-test
pagehelper:
  auto-dialect: true
  close-conn: true
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: pageNum=page;size=size
logging:
  level:
    com.ilikly.finalframework: debug
server:
  port: 8080
final:
  data:
    name-converter:
      column-converter: com.ilikly.finalframework.data.mapping.converter.SimpleNameConverter
      table-converter: com.ilikly.finalframework.data.mapping.converter.SimpleNameConverter
    column-generator:
      default-column-generator: com.ilikly.finalframework.mybatis.generator.BaseColumnGenerator
  json:
    json-service: com.ilikly.finalframework.json.jackson.JacksonJsonService
  response:
    sync-status: false
    interceptor: com.ilikly.finalframework.spring.web.reponse.DefaultResponseInterceptor
