spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&verifyServerCertificate=false&useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true&allowMultiQueries=true
    username: root
    password: Aa000000
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-bean-definition-overriding: false
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
  redis:
    host: localhost
    port: 6379
final:
  spring:
    handler-interceptors:
      trace:
        generator: org.finalframework.core.generator.UUIDTraceGenerator
        exclude-path-patterns:
        path-patterns:
  sharding:
    datasource:
      ds0:
        url: ${spring.datasource.url}
        username: ${spring.datasource.username}
        password: ${spring.datasource.password}
        driver-class-name: ${spring.datasource.driver-class-name}
    sharding-rule:
      tables:
        person:
          logic-table: person
          actual-data-nodes: ds0.person_00${0..9},ds0.person_0${10..99}
          table-sharding-strategy:
            inline:
              sharding-column: age
              algorithm-expression: person_${String.format("%03d",age % 100)}
      #          database-sharding-strategy:
      #            inline:
      #              sharding-column: age
      #              algorithm-expression: ds${age % 2}
      binding-tables: []
      broadcast-tables: []
  json:
    json-service: org.finalframework.json.jackson.JacksonJsonService
  exception:
    global-exception-handler: org.finalframework.data.exception.result.ResultGlobalResultExceptionHandler
  retrofit:
    base-url: http://localhost:8080
    ok-http:
      connect-timeout: 5000
      read-timeout: 2000
      write-time: 2000

logging:
  level:
    org.springframework: warn
    org.finalframework: debug
    org.finalframework.test.dao.mapper: debug
mybatis:
  configuration:
    default-enum-type-handler: org.finalframework.mybatis.handler.EnumTypeHandler
