spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&verifyServerCertificate=false&useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Aa000000
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-bean-definition-overriding: false
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
  redis:
    host: localhost
    port: 6379
final:
  spring:
    handler-interceptors:
      trace:
        generator: org.finalframework.core.generator.UUIDTraceGenerator
        exclude-path-patterns:
        path-patterns:

  sharding:
    datasource:
      ds0:
        url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&verifyServerCertificate=false&useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: Aa000000
        driver-class-name: com.mysql.cj.jdbc.Driver
      ds1:
        url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&verifyServerCertificate=false&useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: Aa000000
        driver-class-name: com.mysql.cj.jdbc.Driver
    sharding-rule:
      tables:
        person:
          logic-table: person
          actual-data-nodes: ds${0..1}.person_0${0..9},ds${0..1}.person_${10..99}
          table-sharding-strategy:
            inline:
              sharding-column: age
              algorithm-expression: person_${String.format("%2d",age % 100)}
          database-sharding-strategy:
            inline:
              sharding-column: age
              algorithm-expression: ds${age % 2}
      binding-tables: []
      broadcast-tables: []
  json:
    json-service: org.finalframework.json.jackson.JacksonJsonService
  exception:
    global-exception-handler: org.finalframework.data.exception.result.ResultGlobalResultExceptionHandler
logging:
  level:
    org.springframework: warn
    org.finalframework: debug
    org.finalframework.test.dao.mapper: debug
mybatis:
  configuration:
    default-enum-type-handler: org.finalframework.mybatis.handler.EnumTypeHandler
