spring:
#  datasource:
  #    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&verifyServerCertificate=false&useSSL=false&requireSSL=false
  #    username: root
  #    password: Aa000000
  main:
    allow-bean-definition-overriding: false
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
  redis:
    host: localhost
    port: 6379
final:
  sharding:
    data-sources:
      ds0:
        url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&verifyServerCertificate=false&useSSL=false&requireSSL=false
        username: root
        password: Aa000000
    table-rules:
      person:
        logic-table: person
        actual-data-nodes: ds0.person_${0..1}
  json:
    json-service: org.finalframework.json.jackson.JacksonJsonService
  exception:
    global-exception-handler: org.finalframework.data.exception.result.ResultGlobalResultExceptionHandler
logging:
  level:
    org.finalframework.test.dao.mapper: DEBUG
