spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&verifyServerCertificate=false&useSSL=false&requireSSL=false
    username: root
    password: Aa000000
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-bean-definition-overriding: false
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
  redis:
    host: localhost
    port: 6379
final:
  sharding:
    datasource:
      ds0:
        url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&verifyServerCertificate=false&useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: Aa000000
        driver-class-name: com.mysql.cj.jdbc.Driver
    sharding-rule:
      tables:
        person:
          logic-table: person
          actual-data-nodes: ds0.person_${0..1}
          table-sharding-strategy:
            inline:
              sharding-column: age
              algorithm-expression: person_${age % 2}
          database-sharding-strategy:
            inline:
              sharding-column: age
              algorithm-expression: ds${age % 2}
      binding-tables: []
      broadcast-tables: []
      default-database-sharding-strategy:
        inline:
          sharding-column:
  json:
    json-service: org.finalframework.json.jackson.JacksonJsonService
  exception:
    global-exception-handler: org.finalframework.data.exception.result.ResultGlobalResultExceptionHandler
logging:
  level:
    org.finalframework.test.dao.mapper: DEBUG
