spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&verifyServerCertificate=false&useSSL=false&requireSSL=false
    username: root
    password: Aa000000
    type: com.zaxxer.hikari.HikariDataSource
final:
  json:
    json-service: org.finalframework.json.jackson.JacksonJsonService