spring:
  datasource:
    driver-class-name: org.h2.Driver
    schema: classpath*:db/schema.sql
    url: jdbc:h2:mem:test
    username: sa
    password: sa
  h2:
    console:
      enabled: true
  application:
    name: "amp"
  cloud:
    bootstrap:
      enabled:
logging:
  level:
    org.ifinal.finalframework: debug
dubbo:
  registry:
    address: zookeeper://localhost:2181
  application:
    name: amp
server:
  port: 8000
