spring:
  datasource:
    url: jdbc:MySql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false
    data-username: root
    data-password: Aa000000
  redis:
    host: localhost
    port: 6379

final:
  zookeeper:
    address: 10.248.224.18:2181
    timeout: 3000