default:
  logo: /assets/img/modules/mayi.png
  name: Final Framework
framework:
  logo: /assets/img/modules/mayi.png
  name: Final Framework
  menus:
    - id: data
      name: Data
      icon: image
      menus:
        - id: annotation
          link: /framework/data/annotation
          mini: AN
          name: Annotation
json:
  logo: /assets/img/modules/json.png
  name: Final Json
mybatis:
  logo: /assets/img/modules/mybatis.jpg
  name: Final Mybatis
  menus:
    - id: handler
      icon: dashboard
      name: 类型处理器
      menus:
        - id: enum-type-handler
          link: /mybatis/handler/enum-type-handler
          name: EnumTypeHandler
          mini: ETH
        - id: json-list-type-handler
          link: /mybatis/handler/json-list-type-handler
          name: JsonListTypeHandler
          mini: JLTH
        - id: json-set-type-handler
          link: /mybatis/handler/json-set-type-handler
          name: JsonSetTypeHandler
          mini: JSTH
    - id: interceptor
      icon: dashboard
      name: 拦截器
      menus:
        - id: pageable-interceptor
          link: /mybatis/inteceptor/pageable-interceptor
          name: PageableInteceptor
          mini: PI
#  Spring Module
spring:
  logo: /assets/img/modules/spring.svg
  name: Final Spring
  menus:
    - id: index
      link: /spring
      icon: dashboard
      name: README
    - id: aop
      icon: image
      name: AOP
      menus:
        - id: cutpoint
          link: /spring/aop/cutpoint
          name: 切入点
          mini: CP
    - id: web
      icon: computer
      name: WEB
      menus:
        - id: converter
          name: 参数转换器
          mini: CT
          menus:
            - id: date-converter
              link: /spring/web/converter/date-converter
              name: DateConverter
              mini: DCT
            - id: enum-converter
              link: /spring/web/converter/enum-converter
              name: EnumConverter
              mini: ECT
        - id: resolver
          name: 参数解析器
          mini: RS
          menus:
            - id: request-json-param
              link: /spring/web/resolver/request-json-param
              name: RequestJsonParam
              mini: RJP
        - id: exception
          name: 异常处理器
          mini: EH
          menus:
            - id: exception-handler
              link: /spring/web/exception/exception-handler
              name: ExceptionHandler
              mini: EH
            - id: global-exception-handler
              link: /spring/web/exception/global-exception-handler
              name: GlobalExceptionHandler
              mini: GEH
            - id: json-exception-handler
              link: /spring/web/exception/json-exception-handler
              name: JsonExceptionHandler
              mini: JEH
        - id: interceptor
          name: 处理器拦截器
          mini: HI
          menus:
            - id: handler-interceptor
              link: /spring/web/interceptor/handler-interceptor
              name: HandlerInterceptor
              mini: HI
            - id: trade-handler-interceptor
              link: /spring/web/interceptor/trace-handler-interceptor
              name: TraceHandlerInterceptor
              mini: THI
cache:
  logo: /assets/img/modules/redis.jpg
  name: Final Cache
  menus:
    - id: index
      link: /cache
      icon: dashboard
      name: README
    - id: annotation
      icon: alternate_email
      name: Annotation
      menus:
        - id: cacheable
          link: /cache/annotation/cacheable
          name: Cacheable
          mini: CA
        - id: cachelock
          link: /cache/annotation/cachelock
          name: CacheLock
          mini: CL
        - id: cachedel
          link: /cache/annotation/cachedel
          name: CacheDel
          mini: CD
        - id: cacheput
          link: /cache/annotation/cacheput
          name: CachePut
          mini: CP
        - id: cacheincrement
          link: /cache/annotation/cacheincrement
          name: CacheIncrement
          mini: CI
        - id: cachevalue
          link: /cache/annotation/cachevalue
          name: CacheValue
          mini: CV

