default:
  logo: /assets/img/modules/mayi.png
  name: Final Framework
json:
  logo: /assets/img/modules/json.png
  name: Final Json
mybatis:
  logo: /assets/img/modules/mybatis.jpg
  name: Final Mybatis
spring:
  logo: /assets/img/modules/spring.svg
  name: Final Spring
  menus:
    - id: index
      link: /spring
      icon: dashboard
      name: README
    - id: aop
      icon: image
      name: AOP
      menus:
        - id: cutpoint
          link: /spring/aop/cutpoint
          name: 切入点
          mini: CP
    - id: web
      icon: image
      name: WEB
      menus:
        - id: converter
          name: 参数转换器
          mini: CT
          menus:
            - id: date-converter
              link: /spring/web/converter/date-converter
              name: DateConverter
              mini: DCT
            - id: enum-converter
              link: /spring/web/converter/enum-converter
              name: EnumConverter
              mini: ECT
        - id: resolver
          name: 参数解析器
          mini: RS
          menus:
            - id: request-json-param
              link: /spring/web/resolver/request-json-param
              name: RequestJsonParam
              mini: RJP

cache:
  logo: /assets/img/modules/redis.jpg
  name: Final Cache
  menus:
    - id: index
      link: /cache
      icon: dashboard
      name: README
    - id: annotation
      icon: alternate_email
      name: Annotation
      menus:
        - id: cacheable
          link: /cache/annotation/cacheable
          name: Cacheable
          mini: CA
        - id: cachelock
          link: /cache/annotation/cachelock
          name: CacheLock
          mini: CL
        - id: cachedel
          link: /cache/annotation/cachedel
          name: CacheDel
          mini: CD
        - id: cacheput
          link: /cache/annotation/cacheput
          name: CachePut
          mini: CP
        - id: cacheincrement
          link: /cache/annotation/cacheincrement
          name: CacheIncrement
          mini: CI
        - id: cachevalue
          link: /cache/annotation/cachevalue
          name: CacheValue
          mini: CV

